version: '2.1'
services:
  nginx:
    image: nginx-amplify
    environment:
    - API_KEY=emotibot
    - AMPLIFY_IMAGENAME=my-service-123
    ports:
    - 80:80
    volumes:
    - /home/deployer/nginx-slb/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/deployer/nginx-slb/conf/conf.d/:/etc/nginx/conf.d/
    - /home/deployer/nginx-slb/html/:/usr/share/nginx/html/
    container_name: nginx
    hostname: nginx