version: '2.1'
services:
  nginx:
    image: nginx:1.13
    ports:
    - 80:80
    volumes:
    - /home/deployer/nginx-slb/conf/nginx.conf:/etc/nginx/nginx.conf
    - /home/deployer/nginx-slb/conf/conf.d/:/etc/nginx/conf.d/
    container_name: nginx
    hostname: nginx